### ISSUE TITLE
V10 deploy checklist

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapventure#305]
- [x] Ensure OSM tile server is publicly-visible
 - [x] Verify version number
 - [x] Perform load test on new services
 - [x] Generate / regenerate cache on AWS deployed instance prior to load test
 - [x] Ensure OpenShift AICC-Fire endpoint is visible outside UAF network
